# Generated by Django 4.1.3 on 2022-11-24 16:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumTag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular tag', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a tag (e.g. Work, School, etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PomodoroTag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular tag', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a tag (e.g. Work, School, etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a tag (e.g. Python, Django, etc.)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular task', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.ManyToManyField(help_text='Select a tag for this task', to='main_app.tasktag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular post', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter a post title', max_length=200)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now, help_text='Enter the date and time the post was posted')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Enter the content of the post', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('upvotes', models.IntegerField(default=0, help_text='Enter the number of upvotes the post has')),
                ('downvotes', models.IntegerField(default=0, help_text='Enter the number of downvotes the post has')),
                ('visits', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(help_text='Select a tag for this post', to='main_app.forumtag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('pomodoro_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular pomodoro', primary_key=True, serialize=False)),
                ('name', models.CharField(default='Pomodoro', help_text='Enter a pomodoro name', max_length=200)),
                ('start_time', models.DateTimeField(default=datetime.datetime.now, help_text='Enter the start time of the pomodoro')),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField(default=25, help_text='Enter the duration of the pomodoro in minutes')),
                ('description', models.CharField(help_text='Enter a description of the pomodoro', max_length=200)),
                ('tags', models.ManyToManyField(help_text='Select a tag for this pomodoro', to='main_app.pomodorotag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular comment', primary_key=True, serialize=False)),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now, help_text='Enter the date and time the comment was posted')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(help_text='Enter the content of the comment', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('upvotes', models.IntegerField(default=0, help_text='Enter the number of upvotes the comment has')),
                ('downvotes', models.IntegerField(default=0, help_text='Enter the number of downvotes the comment has')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.post')),
                ('replies', models.ManyToManyField(blank=True, to='main_app.comment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
