# Generated by Django 4.1.3 on 2022-11-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_comment_updated_remove_post_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('is_admin', 'Can do admin things'),)},
        ),
    ]
