# Generated by Django 4.1.3 on 2022-11-28 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_pomodoro_tags_remove_task_tags_pomodoro_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pomodoro',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='pomodoro',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description of the pomodoro', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pomodoro',
            name='duration',
            field=models.PositiveIntegerField(default=25, help_text='Enter the duration of the pomodoro in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
