# Generated by Django 4.1.3 on 2022-12-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_rename_description_task_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, help_text='Select a tag for this post', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.forumtag'),
        ),
    ]
