# Generated by Django 4.1.3 on 2022-12-05 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0018_alter_post_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular event', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter the title of the event', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Enter the description of the event', max_length=1000, null=True)),
                ('start_time', models.DateTimeField(help_text='Enter the start time of the event')),
                ('end_time', models.DateTimeField(help_text='Enter the end time of the event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
