# Generated by Django 4.1.3 on 2022-12-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='content',
        ),
    ]
