# Generated by Django 4.1.3 on 2022-12-07 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_rename_description_event_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
    ]
