# Generated by Django 4.1.3 on 2022-12-07 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
