# Generated by Django 4.1.3 on 2022-12-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commentable',
            field=models.BooleanField(blank=True, default=True, help_text='Check if you want to allow comments on this post', null=True),
        ),
    ]
