# Generated by Django 4.1.3 on 2022-12-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_post_commentable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentable',
            field=models.BooleanField(default=True, help_text='Check if you want to allow comments on this post'),
        ),
    ]
